### ISSUE TITLE
Update VIC webste for VIC 4.2

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/VIC#154]
As part of releasing VIC 4.2, we need to update the public documentation.  I can do the actual website updates but I will need some help from @tbohn on those issues that I am less familiar with.  Below is a list of the issues requiring new or augmented documentation:
#### New Features and Options:
- [x] #127 Partial vegetation cover - @tbohn 
- [x] #35 Non-climatological time-varying veg parameters - @tbohn 
- [x] #13 New forcing variables for carbon cycle - @tbohn 
- [x] #13 Simulation of photosynthesis - @tbohn 
- [x] #13 Simulation of soil carbon storage and fluxes - @tbohn 
- [x] #118 Soil moisture content for half-space below bottom soil layer (`SLAB_MOIST_FRACT`) - @tbohn 
- [x] #66 New frozen soil options - @tbohn 
#### Removed or Depreciated Options:
- [x] #22 Removed the `DIST_PRCP` option - @jhamman 
- [x] #21 Removed `user_def.h` - @jhamman
- [x] #120 Removed `ARC_SOIL` and `SOIL_DIR` options from global.param.sample - @jhamman
- [x] #65 Removed `LOG_MATRIC` option - @jhamman 
- [x] #38 Removed `EXCESS_ICE` option - @jhamman 
- [x] #39 Removed `SUN1999` albedo option - @jhamman
- [x] #58 Require `JULY_TAVG_SUPPLIED=TRUE` when `COMPUTE_TREELINE=TRUE` - @jhamman 
#### Improved Documentation:
- [x] #55 Definition of `OUT_ROOTMOIST` - @jhamman
- [x] #78 Actual Evaporation > Potential Evaporation - @tbohn  
- [x] #133 Source Code License - @jhamman  
- [x] #49 Formalized release naming conventions - @jhamman

Feel free to add more to this list if I missed anything.
