### ISSUE TITLE
Image Mode Testing Checklist

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/VIC#177]
This is a checklist of items to work through when testing the image mode driver:
- [x] Use of `enum` definition of output variables, specifically ensure that N_OUTVAR_TYPES is the correct size (#175)
- [x] Image mode driver reproduces classic driver output (#576).
- [x] MPI test: single processor and multiple processor produces same output. (#567)
- [x] Exact restarts in image and classic drivers
