### ISSUE TITLE
CESM Driver Todo List

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/VIC#196]
This will be a running to do list as we work on coupling VIC.5 in CESM.  @bartnijssen, @apcraig, and @mabrunke - feel free to make additions or comments to this list.  

#### Infrastructure to Port from VIC-RASM.1.0
- [ ] Monthly averaging: `wrf_write_data.c`, if only in concept (#198, #281)

#### Science/Physics Options and Features to Port from VIC-RASM.1.0
- [ ] Vegetation dependent snow albedo (RACM: r370)
- [ ] Longwave/emissivity (RASM: r790)
- [ ] Lowest WRF model level height (RASM: r?)

#### New Infrastructure:
- [x] CESM build system integration
- [x] C-Fortran Interface
  - [x] `vic_cesm_init_mpi(MPI_COMMUNICATOR);`
  - [x] `vic_cesm_init(clock, case_metadata);` :  Initialization call from `lnd_init_mct()`.
  - [x] `vic_cesm_run(clock);`:  Run call from `lnd_run_mct()` including forcing data from the coupler `x2l` and `l2x` returning fluxes.
  - [x] `vic_cesm_final();`:  Free memory, this can be called directly from Fortran.

#### New Science/Physics Features
- [ ] Carbon and Dynamic Vegetation (CN-DV) from @mabrunke. (#174)

#### Testing (in addition to other VIC testing in #79 and #177)
- [ ] Exact restarts in CESM
- [ ] Image mode driver results match `RI` compset results

#### Last Steps
- [ ] Initial state generation for VIC and eventually, CN

**Comment by jhamman** [comment]
This table outlines the variables that are should not be set by VIC's global parameter file in the CESM driver and details where those variables will be set.  Variables labeled with *n/a* are not to be used by this driver.

| Variables Removed From Global Parameter File | Where set in CESM driver       | Notes                                                                            |
|----------------------------------------------|--------------------------------|----------------------------------------------------------------------------------|
| STARTYEAR                                    | `vic_cesm_init`                |                                                                                  |
| STARTMONTH                                   | `vic_cesm_init`                |                                                                                  |
| STARTDAY                                     | `vic_cesm_init`                |                                                                                  |
| STARTSEC                                     | `vic_cesm_init`                |                                                                                  |
| NRECS                                        | n/a                            | calculated from start/stop date                                                  |
| ENDYEAR                                      | `vic_cesm_init`                |                                                                                  |
| ENDMONTH                                     | `vic_cesm_init`                |                                                                                  |
| ENDDAY                                       | `vic_cesm_init`                |                                                                                  |
| CALENDAR                                     | `vic_cesm_init`                |                                                                                  |
| STANDARD                                     | `vic_cesm_init`                |                                                                                  |
| FULL_ENERGY                                  | n/a                            | hard coded                                                                       |
| CONTINUEONERROR                              | `vic_cesm_init`                |                                                                                  |
| EQUAL_AREA                                   | n/a                            | set via domain area                                                              |
| RESOLUTION                                   | n/a                            | set via domain area                                                              |
| LOG_DIR                                      | `vic_cesm_init`                | typically this is `$CWD`                                                         |
| INIT_STATE                                   | `vic_cesm_init`                | need to add rpointer functionality                                               |
| STATENAME                                    | `vic_cesm_init` and `vic_cesm_run` | state flag will be raised and name will be determined from the current timestamp |
| STATEYEAR                                    | n/a                            |                                                                                  |
| STATEMONTH                                   | n/a                            |                                                                                  |
| STATEDAY                                     | n/a                            |                                                                                  |
| BINARY_STATE_FILE                            | n/a                            |                                                                                  |
| FORCING1                                     | n/a                            |                                                                                  |
| FORCING2                                     | n/a                            |                                                                                  |
| FORCE_FORMAT                                 | n/a                            |                                                                                  |
| FORCE_ENDIAN                                 | n/a                            |                                                                                  |
| N_TYPES                                      | n/a                            |                                                                                  |
| FORCE_STEPS_PER_DAY                          | `vic_cesm_init`                |                                                                                  |
| FORCEYEAR                                    | n/a                            |                                                                                  |
| FORCEMONTH                                   | n/a                            |                                                                                  |
| FORCEDAY                                     | n/a                            |                                                                                  |
| FORCESEC                                     | n/a                            |                                                                                  |
| GRID_DECIMAL                                 | n/a                            |                                                                                  |
| ALMA_INPUT                                   | n/a                            | hard coded / will decode coupled inputs on the fly                               |
| DOMAIN                                       | `vic_cesm_init`                |                                                                                  |
| SKIPYEAR                                     | n/a                            |                                                                                  |
| COMPRESS                                     | n/a                            |                                                                                  |
| BINARY_OUTPUT                                | n/a                            |                                                                                  |
| PRT_HEADER                                   | n/a                            |                                                                                  |
| PRT_SNOW_BAND                                | n/a                            |                                                                                  |

**Comment by jhamman** [comment]
This line change needs to be added to 

```diff
Joes-Air:~/Dropbox/src/rasm/scripts$ svn diff
Index: create_newcase
===================================================================
--- create_newcase	(revision 1204)
+++ create_newcase	(working copy)
@@ -879,6 +879,7 @@
 	    my $blddir;
 	    if ($model eq 'COMP_ATM') {$blddir = "$ccsmroot/models/atm/$comp/bld"}; 
 	    if ($model eq 'COMP_LND') {$blddir = "$ccsmroot/models/lnd/$comp/bld"}; 
+	    if ($compl eq 'vic'     ) {$blddir = "$ccsmroot/models/lnd/vic/vic/drivers/cesm/bld"}; 
 	    if ($model eq 'COMP_ICE') {$blddir = "$ccsmroot/models/ice/$comp/bld"}; 
 	    if ($model eq 'COMP_OCN') {$blddir = "$ccsmroot/models/ocn/$comp/bld"}; 
 	    if ($model eq 'COMP_GLC') {$blddir = "$ccsmroot/models/glc/$comp/bld"}; 
```

**Comment by jhamman** [comment]
I have just opened individual issues for the remaining issues in this todo list. We can continue discussion on the individual issues.  Closed via #397.
