### ISSUE TITLE
DOC: Update documentation website for VIC 5 release

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/VIC#465]
This issue is the master list of documentation improvements that need to be made prior to releasing VIC 5. See the individual issues for more information and discussion.

#### User Guide
- [x] [Image Driver: VIC Model Inputs](http://vic.readthedocs.org/en/develop/Documentation/Drivers/Image/Inputs/) - xref: #469.
- [x] [Image Driver: VIC Model Outputs](http://vic.readthedocs.org/en/develop/Documentation/Drivers/Image/Outputs/) - xref: #470.
- [x] [CESM Driver: Configuring VIC using the CESM driver](http://vic.readthedocs.org/en/develop/Documentation/Drivers/CESM/CESMDriver/#configuring-vic-as-the-land-surface-component-in-cesm) - xref: #471.

#### Development
- [x] [Release Notes](http://vic.readthedocs.org/en/develop/Development/ReleaseNotes/)
- [x] [Test System](http://vic.readthedocs.org/en/develop/Development/Testing/) - xref: #472.

#### Downloads
- [x] [Datasets](http://vic.readthedocs.org/en/develop/Datasets/Datasets/)
